# Generated by Django 4.2.10 on 2024-05-12 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media')),
                ('i_descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=64)),
                ('p_descrip', models.TextField()),
                ('p_monto_ini', models.FloatField()),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_prod', to='auctions.categoria')),
                ('id_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_prod', to='auctions.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_nombre', models.CharField(max_length=64)),
                ('s_descrip', models.TextField()),
                ('s_fecha_ini', models.DateField()),
                ('s_fecha_fin', models.DateField()),
                ('s_estado', models.BooleanField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_subasta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_monto', models.FloatField()),
                ('id_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_subasta', to='auctions.subasta')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_oferta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_coment', models.TextField()),
                ('id_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subasta_comentario', to='auctions.subasta')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comentario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subastado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_subastado', to='auctions.producto')),
                ('id_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subasta', to='auctions.subasta')),
            ],
            options={
                'unique_together': {('id_subasta', 'id_producto')},
            },
        ),
    ]
