# Generated by Django 4.2.10 on 2024-06-06 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comentario_c_fecha_oferta_o_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='c_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 7, 57, 17, 317986, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='o_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 7, 57, 17, 317986, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 7, 57, 17, 317986, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_ini',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 7, 57, 17, 317986, tzinfo=datetime.timezone.utc)),
        ),
    ]
