# Generated by Django 4.2.10 on 2024-09-07 11:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_comentario_c_fecha_alter_oferta_o_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subasta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='auctions.subasta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='c_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 7, 11, 26, 415443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='o_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 7, 11, 26, 415443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 7, 11, 26, 415443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_ini',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 7, 11, 26, 415443, tzinfo=datetime.timezone.utc)),
        ),
    ]
