# Generated by Django 4.2.10 on 2024-09-14 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_producto_subasta_alter_comentario_c_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_imagen',
        ),
        migrations.AddField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='auctions.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='c_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 6, 59, 40, 217279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='o_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 6, 59, 40, 217279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 6, 59, 40, 217279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_ini',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 6, 59, 40, 217279, tzinfo=datetime.timezone.utc)),
        ),
    ]
