# Generated by Django 4.2.10 on 2024-09-24 09:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comentario_c_fecha_alter_imagen_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='c_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 5, 18, 59, 28491, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='o_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 5, 18, 59, 28491, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 5, 18, 59, 28491, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_ini',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 5, 18, 59, 28491, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('w_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.producto')),
            ],
        ),
    ]
