# Generated by Django 4.2.10 on 2024-09-26 20:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_subastado_won_user_alter_comentario_c_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id_subasta',
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_comentario', to='auctions.producto'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='c_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 16, 33, 45, 498244, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='o_fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 16, 33, 45, 498244, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 16, 33, 45, 498244, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='s_fecha_ini',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 16, 33, 45, 498244, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subastado',
            name='won_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_won_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
